# Generated by Django 4.2.27 on 2025-12-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='age_group',
            field=models.CharField(default=-2, max_length=20),
            preserve_default=False,
        ),
    ]
