# Generated by Django 4.2.27 on 2025-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='task',
            name='age_group',
            field=models.CharField(choices=[('3-5', 'Ages 3–5'), ('6-8', 'Ages 6–8'), ('9-11', 'Ages 9–11'), ('12+', 'Ages 12+')], max_length=20),
        ),
    ]
