# Generated by Django 4.2.27 on 2025-12-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options_alter_task_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='age_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ages 3–5'), (2, 'Ages 6–8'), (3, 'Ages 9–11'), (4, 'Ages 12+')]),
        ),
    ]
